name: Trash Club
markdown: kramdown
collections:
  - events
  - readings
  - projects
  - resources
paginate: 5
paginate_path: "/blog/:num/"
plugins: [jekyll-paginate]
permalink: /blog/:year/:month/:day/:title/